export const hostelImages = {
  "dostel-kasol-parvati-valley": [
    "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&q=85",
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80",
    "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80",
  ],
  "dostel-goa-beach": [
    "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=85",
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    "https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=800&q=80",
    "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
  ],
  default: [
    "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1200&q=85",
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80",
    "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
  ],
};

export const hostelRooms = [
  {
    id: "mixed-dorm-6",
    name: "Mixed Dorm (6 Bed)",
    type: "dorm",
    price: 327,
    originalPrice: 450,
    capacity: 6,
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",
    amenities: ["Locker", "Reading Light", "Power Socket", "Privacy Curtain", "Hot Shower"],
    available: true,
  },
  {
    id: "female-dorm-4",
    name: "Female Only Dorm (4 Bed)",
    type: "dorm",
    price: 399,
    originalPrice: 550,
    capacity: 4,
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",
    amenities: ["Locker", "Reading Light", "Power Socket", "Privacy Curtain", "Female Only"],
    available: true,
  },
  {
    id: "private-room",
    name: "Private Room",
    type: "private",
    price: 1299,
    originalPrice: 1800,
    capacity: 2,
    image: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=600&q=80",
    amenities: ["AC", "TV", "Attached Bath", "Hot Shower", "WiFi", "Housekeeping"],
    available: true,
  },
  {
    id: "deluxe-private",
    name: "Deluxe Private Room",
    type: "private",
    price: 1799,
    originalPrice: 2400,
    capacity: 2,
    image: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=600&q=80",
    amenities: ["AC", "TV", "Attached Bath", "Mountain View", "Balcony", "WiFi"],
    available: false,
  },
];

export const hostelFAQs = [
  {
    q: "Where is this hostel located?",
    a: "The hostel is centrally located with easy access to major attractions, transport hubs and local markets.",
  },
  {
    q: "What is the check-in and check-out time?",
    a: "Check-in: 2 PM | Check-out: 11 AM. Early check-in or late checkout is subject to availability and may incur additional charges.",
  },
  {
    q: "Are female-only dorms available?",
    a: "Yes, dedicated female-only dormitories are available. These are exclusively reserved for female guests.",
  },
  {
    q: "Do rooms have attached washrooms?",
    a: "Yes, all private rooms have en-suite bathrooms. Dorms share common clean washrooms with 24hr hot water.",
  },
  {
    q: "Is there a rooftop or terrace?",
    a: "Yes, we have a rooftop café with stunning views.",
  },
  {
    q: "Are there indoor games available?",
    a: "Yes — board games, UNO, Jenga, and foosball table available in the common area.",
  },
  {
    q: "Is the hostel pet-friendly?",
    a: "Yes! Pets are permitted in Private Rooms only and strictly not allowed in shared dorms.",
  },
  {
    q: "Is first aid available at the property?",
    a: "Yes, first aid is on-site and local doctors can be called upon if needed.",
  },
];

export const hostelPolicies = [
  "Hostel is suited for young backpacking travellers. Guests below 18 years are not admitted even with guardians.",
  "Outside food is strictly prohibited inside the hostel.",
  "Possession or consumption of illegal drugs is strictly prohibited. Alcohol is prohibited.",
  "100% prepayment is mandatory on or prior to check-in.",
  "Mandatory pre-arrival check-in via mobile app. Govt. approved photo ID required at check-in.",
  "Visitors are allowed only in waiting areas/common spaces — not in any rooms at any time.",
  "Any misconduct, harassment or behaviour disruptive to other guests results in immediate termination without refund.",
  "Group of 2+ guests: same dorm room not guaranteed, allocation is subject to availability.",
];

export const hostelWhyLove = [
  {
    icon: "🌏",
    title: "Cultural hot pot",
    desc: "Travellers from around the globe reside here, making it super culturally rich and full of unique experiences.",
  },
  {
    icon: "🥾",
    title: "Camping & trekking",
    desc: "Take the opportunity to trek gorgeous trails and explore the surrounding wilderness.",
  },
  {
    icon: "🎨",
    title: "Bohemian feel",
    desc: "Designed to soothe and comfort, full of relaxing nooks and crannies to de-stress your soul.",
  },
  {
    icon: "☕",
    title: "Best café, best views",
    desc: "Our café provides lip-smacking food and drop-dead gorgeous views of the landscape beyond.",
  },
];

export const blogPosts = [
  {
    slug: "10-reasons-kasol-perfect-getaway",
    title: "10 Reasons why Kasol is the perfect pre-winter getaway",
    readTime: "4 mins read",
    date: "26 Mar, 2023",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
    excerpt: "North India's stunning Kasol is every backpacker's paradise. Read on for the top reasons that make it the perfect pre-winter getaway.",
  },
  {
    slug: "10-villages-near-kasol",
    title: "10 Villages near Kasol that every backpacker must explore",
    readTime: "4 mins read",
    date: "06 Jul, 2023",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    excerpt: "The little hamlet of Kasol is a haven for backpackers but surrounding it are some lesser known villages worth exploring.",
  },
  {
    slug: "4-treks-near-kasol-beginners",
    title: "Don't miss these 4 treks near Kasol for beginners",
    readTime: "2 mins read",
    date: "20 Mar, 2023",
    image: "https://images.unsplash.com/photo-1544198365-f5d60b6d8190?w=600&q=80",
    excerpt: "Located in Himachal Pradesh, Kasol has many adventurous trekking trails. Here are 4 treks you should definitely try.",
  },
  {
    slug: "best-cafes-kasol",
    title: "Explore these 8 best cafes in Kasol to satisfy your cravings",
    readTime: "4 mins read",
    date: "07 Mar, 2023",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&q=80",
    excerpt: "Discover the ultimate food adventure in Kasol — from traditional Himalayan cuisine to international delights.",
  },
];

export const amenitiesList = [
  { icon: "❄️", label: "Air conditioner" },
  { icon: "🔥", label: "Bonfire" },
  { icon: "📷", label: "CCTV" },
  { icon: "🛋️", label: "Common area" },
  { icon: "🧹", label: "Housekeeping" },
  { icon: "🎮", label: "Indoor games" },
  { icon: "🅿️", label: "Parking" },
  { icon: "🐾", label: "Pet friendly" },
  { icon: "⚡", label: "Power backup" },
  { icon: "☕", label: "Veg café" },
  { icon: "📶", label: "Wi-Fi" },
  { icon: "💻", label: "Workation" },
  { icon: "🚿", label: "Hot shower" },
  { icon: "🔒", label: "Lockers" },
  { icon: "🎬", label: "Movie screening" },
  { icon: "🏔️", label: "Mountain view" },
];

export const hostels = [
  {
    slug: "dostel-vattakanal",
    name: "Dostel Vattakanal",
    tagline: "A community hostel in the Kodaikanal mountains",
    location: "Vattakanal, Kodaikanal",
    address: "Vattakanal village, Kodaikanal, Tamil Nadu",
    price: 327,
    rating: 4.8,
    reviews: 1240,
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80",
    tags: ["Mountains", "Community", "Workation"],
    category: "mountains",
    isNew: false,
    isTrending: true,
    amenities: ["Wi-Fi", "Altaf's Cafe", "Hot water", "Common room", "Bonfire pit", "Indoor games", "Housekeeping", "Power backup", "Lockers", "Pet friendly", "Mountain views"],
    description: "Set against the misty forests of Vattakanal, Dostel is a backpacker hostel with soul. Founded on land restored by Bob & Tanya in 1985, it's become a gathering place for solo travelers, friend groups, families, and remote workers who want more than a bed — they want community.",
    checkIn: "2 PM",
    checkOut: "11 AM",
    guestVisit: "10 AM – 8 PM",
    nearbyTrain: "Kodai Road Railway Station – 80 km (2.5 hr by cab)",
    nearbyBus: "Kodaikanal Bus Stand – 3 km (15 min by auto)",
    nearbyAirport: "Madurai Airport – 135 km (4 hr by cab)",
    maxCapacity: 110,
  },
  {
    slug: "dostel-goa-beach",
    name: "Goa, Anjuna Beach",
    tagline: "Goan Fiesta Vibes",
    location: "Anjuna, Goa",
    address: "Near St. Anthony's Chapel, Anjuna, North Goa, 403509",
    price: 499,
    rating: 4.7,
    reviews: 2100,
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    tags: ["Beach", "Party", "Chill"],
    category: "beach",
    isNew: false,
    isTrending: true,
    amenities: ["Wi-Fi", "Pool", "Common area", "Housekeeping", "Indoor games", "Parking", "CCTV", "Hot shower", "Veg café", "Power backup"],
    description: "Party, chill and unwind at our Goa hostel — steps from the iconic Anjuna beach with the best vibes in town. Dive into the pool, watch sunsets with new friends, and wake up to the sound of waves.",
    checkIn: "2 PM",
    checkOut: "11 AM",
    guestVisit: "9 AM – 9 PM",
    nearbyTrain: "Thivim railway station – 22 km",
    nearbyBus: "Mapusa bus stand – 8 km",
    nearbyAirport: "Goa International Airport (Dabolim) – 45 km",
    maxCapacity: 80,
  },
  {
    slug: "dostel-delhi-airport",
    name: "Delhi, International Airport",
    tagline: "Land, Chill & Take Off",
    location: "New Delhi",
    address: "Aerocity, IGI Airport, New Delhi – 110037",
    price: 552,
    rating: 4.6,
    reviews: 870,
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80",
    tags: ["City", "Transit", "Budget"],
    category: "city",
    isNew: true,
    isTrending: false,
    amenities: ["Wi-Fi", "AC", "Common area", "Housekeeping", "CCTV", "Hot shower", "Veg café", "Power backup", "Lockers", "24hr Reception"],
    description: "The perfect transit hostel near Delhi airport. Sleep, refresh and catch your next flight completely stress-free. With shuttle connectivity and 24hr reception, we have you covered.",
    checkIn: "2 PM",
    checkOut: "11 AM",
    guestVisit: "9 AM – 9 PM",
    nearbyTrain: "New Delhi Railway Station – 18 km",
    nearbyBus: "ISBT Kashmere Gate – 20 km",
    nearbyAirport: "IGI Airport – 3 km",
    maxCapacity: 60,
  },
  {
    slug: "dostel-bangalore-hsr",
    name: "Bangalore, HSR Layout",
    tagline: "Work, Wander, Repeat",
    location: "HSR Layout, Bangalore",
    address: "Sector 2, HSR Layout, Bengaluru – 560102",
    price: 519,
    rating: 4.7,
    reviews: 560,
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80",
    tags: ["Workation", "City", "Tech"],
    category: "workation",
    isNew: false,
    isTrending: true,
    amenities: ["Wi-Fi", "AC", "Common area", "Housekeeping", "CCTV", "Hot shower", "Veg café", "Power backup", "Workation", "Indoor games"],
    description: "Designed for the modern nomad. Work from our state-of-the-art co-working space and explore Bangalore's vibrant food scene by night. High-speed fibre WiFi and dedicated desks included.",
    checkIn: "2 PM",
    checkOut: "11 AM",
    guestVisit: "9 AM – 9 PM",
    nearbyTrain: "KSR Bangalore City Station – 12 km",
    nearbyBus: "Majestic KSRTC – 12 km",
    nearbyAirport: "Kempegowda International Airport – 38 km",
    maxCapacity: 50,
  },
  {
    slug: "dostel-jaipur-mi-road",
    name: "Jaipur, MI Road",
    tagline: "Royal Way of Celebration",
    location: "MI Road, Jaipur",
    address: "Near Panch Batti, MI Road, Jaipur, Rajasthan – 302001",
    price: 426,
    rating: 4.8,
    reviews: 990,
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80",
    tags: ["Heritage", "Spiritual", "Culture"],
    category: "heritage",
    isNew: false,
    isTrending: false,
    amenities: ["Wi-Fi", "Common area", "Housekeeping", "Indoor games", "CCTV", "Hot shower", "Veg café", "Power backup", "Rooftop"],
    description: "Soak in the regal charm of the Pink City from our rooftop hostel in the heart of Jaipur. Walking distance from Hawa Mahal, local markets and the finest Rajasthani cuisine.",
    checkIn: "2 PM",
    checkOut: "11 AM",
    guestVisit: "9 AM – 9 PM",
    nearbyTrain: "Jaipur Junction – 3 km",
    nearbyBus: "Sindhi Camp Bus Stand – 1 km",
    nearbyAirport: "Jaipur International Airport – 12 km",
    maxCapacity: 70,
  },
  {
    slug: "dostel-coorg-rainforest",
    name: "Coorg Rainforest, Madikeri",
    tagline: "Coffee, Tea, Spices & More",
    location: "Madikeri, Coorg",
    address: "Galibeedu, Madikeri, Coorg, Karnataka – 571201",
    price: 589,
    rating: 4.9,
    reviews: 720,
    image: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=800&q=80",
    tags: ["Mountains", "Nature", "Jungle"],
    category: "jungle",
    isNew: false,
    isTrending: true,
    amenities: ["Wi-Fi", "Bonfire", "Common area", "Housekeeping", "Indoor games", "Parking", "Pet friendly", "CCTV", "Hot shower", "Veg café"],
    description: "Wake up to misty coffee plantation views in this forest retreat — the most serene escape from city life. Nestled in 10 acres of rainforest with waterfalls steps away.",
    checkIn: "2 PM",
    checkOut: "11 AM",
    guestVisit: "9 AM – 9 PM",
    nearbyTrain: "Mysore Junction – 120 km",
    nearbyBus: "Madikeri Bus Stand – 5 km",
    nearbyAirport: "Mangalore International Airport – 135 km",
    maxCapacity: 45,
  },
  {
    slug: "dostel-dharamshala",
    name: "Dharamshala",
    tagline: "360 Degree Panoramic Views",
    location: "Dharamshala, Himachal Pradesh",
    address: "Old Dharamshala, HP 176215",
    price: 337,
    rating: 4.7,
    reviews: 1050,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    tags: ["Mountains", "Spiritual", "Offbeat"],
    category: "mountains",
    isNew: false,
    isTrending: false,
    amenities: ["Wi-Fi", "Bonfire", "Common area", "Housekeeping", "CCTV", "Hot shower", "Veg café", "Power backup"],
    description: "Breathtaking views of the Dhauladhar range from your bed. The ultimate Himalayan hostel experience with yoga spaces, trekking access and a rooftop to die for.",
    checkIn: "2 PM",
    checkOut: "11 AM",
    guestVisit: "9 AM – 9 PM",
    nearbyTrain: "Pathankot Junction – 90 km",
    nearbyBus: "Dharamshala Bus Stand – 2 km",
    nearbyAirport: "Gaggal Airport (Kangra) – 13 km",
    maxCapacity: 55,
  },
  {
    slug: "dostel-gokarna",
    name: "Gokarna",
    tagline: "Joy of Festi-Waves",
    location: "Gokarna, Karnataka",
    address: "Near Om Beach, Gokarna, Karnataka – 581326",
    price: 519,
    rating: 4.6,
    reviews: 640,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    tags: ["Beach", "Spiritual", "Nature"],
    category: "beach",
    isNew: false,
    isTrending: true,
    amenities: ["Wi-Fi", "Bonfire", "Common area", "Housekeeping", "CCTV", "Hot shower", "Veg café", "Parking", "Pet friendly"],
    description: "A peaceful beach town where spiritual seekers and party people co-exist. Om Beach is literally at your doorstep — temples, tides and bonfires.",
    checkIn: "2 PM",
    checkOut: "11 AM",
    guestVisit: "9 AM – 9 PM",
    nearbyTrain: "Gokarna Road Railway Station – 10 km",
    nearbyBus: "Gokarna Town Bus Stand – 2 km",
    nearbyAirport: "Dabolim Goa Airport – 140 km",
    maxCapacity: 40,
  },
];

export const categories = [
  { id: "all", label: "All", icon: "🏠" },
  { id: "mountains", label: "Mountains", icon: "⛰️" },
  { id: "beach", label: "Beach", icon: "🏖️" },
  { id: "city", label: "City", icon: "🏙️" },
  { id: "jungle", label: "Jungle", icon: "🌿" },
  { id: "heritage", label: "Heritage", icon: "🏰" },
  { id: "workation", label: "Workation", icon: "💻" },
  { id: "adventure", label: "Adventure", icon: "🧗" },
  { id: "spiritual", label: "Spiritual", icon: "🛕" },
  { id: "offbeat", label: "Offbeat", icon: "🗺️" },
  { id: "party", label: "Party", icon: "🎉" },
  { id: "central", label: "Central", icon: "📍" },
  { id: "north", label: "North", icon: "🧭" },
  { id: "south", label: "South", icon: "🌴" },
  { id: "monsoon", label: "Monsoon", icon: "🌧️" },
  { id: "new", label: "New", icon: "✨" },
  { id: "trending", label: "Trending", icon: "🔥" },
];

export const eventCategories = [
  { id: "all", label: "All", icon: "🌐" },
  { id: "trekking", label: "Trekking", icon: "🥾" },
  { id: "adventure", label: "Adventure", icon: "🧗" },
  { id: "day-tour", label: "Day Tour", icon: "🚌" },
  { id: "heritage", label: "Heritage", icon: "🏛️" },
  { id: "jungle", label: "Jungle", icon: "🌿" },
  { id: "spiritual", label: "Spiritual", icon: "🛕" },
  { id: "networking", label: "Networking", icon: "🤝" },
  { id: "nature", label: "Nature", icon: "🌄" },
  { id: "leisure", label: "Leisure", icon: "🏖️" },
  { id: "party", label: "Party", icon: "🎉" },
  { id: "creativity", label: "Creativity", icon: "🎨" },
  { id: "beach", label: "Beach", icon: "🌊" },
];

export const events = [
  {
    slug: "kasol-music-festival",
    title: "Kasol Music Festival",
    date: "Aug 15–17, 2025",
    startDate: "2025-08-15",
    endDate: "2025-08-17",
    location: "Kasol, Himachal Pradesh",
    hostel: "dostel-kasol-parvati-valley",
    price: 1999,
    originalPrice: 2799,
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    category: "party",
    categoryLabel: "Music",
    description: "3 days of live music, bonfires and mountain vibes in the Parvati Valley. Curated artists, camping under stars.",
    maxParticipants: 200,
    spotsLeft: 34,
    duration: "3 Days / 2 Nights",
  },
  {
    slug: "goa-beach-bonanza",
    title: "Goa Beach Bonanza",
    date: "Sep 1–3, 2025",
    startDate: "2025-09-01",
    endDate: "2025-09-03",
    location: "Anjuna, Goa",
    hostel: "dostel-goa-beach",
    price: 2499,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800&q=80",
    category: "beach",
    categoryLabel: "Beach Party",
    description: "Sunsets, DJs, bonfire nights and more on the shores of Goa's best beaches. Stay is included.",
    maxParticipants: 150,
    spotsLeft: 22,
    duration: "3 Days / 2 Nights",
  },
  {
    slug: "himalayan-trek-camp",
    title: "Himalayan Trek & Camp",
    date: "Oct 5–10, 2025",
    startDate: "2025-10-05",
    endDate: "2025-10-10",
    location: "Manali, Himachal Pradesh",
    hostel: "dostel-dharamshala",
    price: 4999,
    originalPrice: 6500,
    image: "https://images.unsplash.com/photo-1544198365-f5d60b6d8190?w=800&q=80",
    category: "trekking",
    categoryLabel: "Adventure",
    description: "6-day guided trek through breathtaking Himalayan landscapes with camping, meals and guide included.",
    maxParticipants: 30,
    spotsLeft: 8,
    duration: "6 Days / 5 Nights",
  },
  {
    slug: "coorg-coffee-trail",
    title: "Coorg Coffee Trail & Waterfalls",
    date: "Aug 22–24, 2025",
    startDate: "2025-08-22",
    endDate: "2025-08-24",
    location: "Madikeri, Coorg",
    hostel: "dostel-coorg-rainforest",
    price: 2999,
    originalPrice: 3800,
    image: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=800&q=80",
    category: "nature",
    categoryLabel: "Nature",
    description: "Explore coffee plantations, hidden waterfalls and jungle trails. All meals, stay and activities included.",
    maxParticipants: 40,
    spotsLeft: 15,
    duration: "3 Days / 2 Nights",
  },
  {
    slug: "jaipur-heritage-walk",
    title: "Jaipur Royal Heritage Walk",
    date: "Sep 14, 2025",
    startDate: "2025-09-14",
    endDate: "2025-09-14",
    location: "Jaipur, Rajasthan",
    hostel: "dostel-jaipur-mi-road",
    price: 799,
    originalPrice: 1200,
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80",
    category: "heritage",
    categoryLabel: "Heritage",
    description: "A curated walking tour through the Pink City's forts, palaces and hidden bazaars with a local expert.",
    maxParticipants: 25,
    spotsLeft: 12,
    duration: "1 Day",
  },
  {
    slug: "delhi-night-food-tour",
    title: "Old Delhi Night Food Tour",
    date: "Aug 30, 2025",
    startDate: "2025-08-30",
    endDate: "2025-08-30",
    location: "Old Delhi",
    hostel: "dostel-delhi-airport",
    price: 599,
    originalPrice: 900,
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    category: "day-tour",
    categoryLabel: "Day Tour",
    description: "Dive into 10+ street food stops across Chandni Chowk, Jama Masjid and Paranthe Wali Gali.",
    maxParticipants: 20,
    spotsLeft: 6,
    duration: "4 Hours",
  },
];

export const heroSlides = [
  {
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1920&q=85",
    title: "Wake up to adventures",
    subtitle: "India's best hostel network",
  },
  {
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1920&q=85",
    title: "Mountains calling",
    subtitle: "From ₹327/night",
  },
  {
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1920&q=85",
    title: "Beach, vibes, repeat",
    subtitle: "Goa to Gokarna",
  },
  {
    image: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=1920&q=85",
    title: "Coffee & clouds",
    subtitle: "Coorg, Wayanad & more",
  },
];

export const trustBadges = [
  { icon: "🏔️", label: "Real Vattakanal hostel since 1985" },
  { icon: "☕", label: "Altaf's Cafe on property" },
  { icon: "🔥", label: "Campfire & community nights" },
  { icon: "✅", label: "Free cancellation — no booking fees" },
  { icon: "🌿", label: "Ecologically restored grounds" },
  { icon: "📞", label: "24hr reception + local support" },
];

export const dostellerTiers = [
  {
    id: "bronze",
    name: "Bronze",
    price: 0,
    period: "free" as const,
    description: "Community access, always free",
    benefits: ["Community access", "Member directory", "Event notifications", "Dosteller badge"],
    ctaLabel: "Join free",
    highlighted: false,
    color: "stone",
  },
  {
    id: "silver",
    name: "Silver",
    price: 999,
    period: "/yr" as const,
    description: "Save ₹3,000+ on a single trip",
    benefits: ["Everything in Bronze", "15% off all stays", "Free member events", "Early booking access"],
    ctaLabel: "Join Silver",
    highlighted: true,
    color: "stone",
  },
  {
    id: "gold",
    name: "Gold",
    price: 2499,
    period: "/yr" as const,
    description: "Our best value — all perks unlocked",
    benefits: ["Everything in Silver", "25% off all stays", "Priority booking", "Exclusive events", "Dedicated support"],
    ctaLabel: "Join Gold",
    highlighted: false,
    color: "sunset",
  },
];

export const dostellerTestimonials = [
  {
    name: "Priya S.",
    location: "Bangalore",
    text: "Stayed 3 weeks in Kasol and made friends for life. The Dosteller community is something special — shared meals, treks, and late-night conversations.",
    tier: "Silver",
    avatar: "👩🏽‍💻",
  },
  {
    name: "Arjun M.",
    location: "Mumbai",
    text: "Saved over ₹8,000 on my stays this year with Gold membership. The priority booking means I never miss out on popular weekends.",
    tier: "Gold",
    avatar: "👨🏾‍🎓",
  },
  {
    name: "Lena K.",
    location: "Berlin",
    text: "Found my remote work tribe at Dostel Coorg. The 40% monthly discount as a Dosteller made my 2-month stay incredibly affordable.",
    tier: "Silver",
    avatar: "👩🏼‍💻",
  },
];

export const dostellerEvents = [
  {
    slug: "kasol-photography-walk",
    title: "Kasol Photography Walk",
    date: "Aug 20, 2025",
    location: "Kasol, HP",
    image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=600&q=80",
    memberPrice: 299,
    regularPrice: 599,
    spotsLeft: 12,
  },
  {
    slug: "coorg-coffee-workshop",
    title: "Coorg Coffee Cupping",
    date: "Sep 5, 2025",
    location: "Madikeri, Coorg",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    memberPrice: 499,
    regularPrice: 899,
    spotsLeft: 8,
  },
  {
    slug: "goa-sunset-yoga",
    title: "Sunset Yoga by the Beach",
    date: "Sep 12, 2025",
    location: "Anjuna, Goa",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&q=80",
    memberPrice: 0,
    regularPrice: 299,
    spotsLeft: 20,
  },
];

export const dostellerBadges = [
  { id: "trailblazer", name: "Trailblazer", icon: "🥾", unlocked: true, criteria: "Book 3 stays" },
  { id: "storyteller", name: "Storyteller", icon: "✍️", unlocked: true, criteria: "Write 3 reviews" },
  { id: "social-butterfly", name: "Social Butterfly", icon: "🦋", unlocked: false, criteria: "Attend 2 events" },
  { id: "remote-pro", name: "Remote Pro", icon: "💻", unlocked: false, criteria: "Book workation 2x" },
  { id: "hometown-hero", name: "Hometown Hero", icon: "🏠", unlocked: false, criteria: "Stay 30+ nights" },
  { id: "early-adopter", name: "Early Adopter", icon: "⭐", unlocked: true, criteria: "Joined in first 6 months" },
];
